export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export type MuscleGroup =
  | "Chest"
  | "Back"
  | "Shoulders"
  | "Biceps"
  | "Triceps"
  | "Forearms"
  | "Legs"
  | "Glutes"
  | "Calves"
  | "Core"
  | "Full body"
  | "Mobility";

export type Equipment =
  | "Bodyweight"
  | "Pull-up bar"
  | "Dumbbell"
  | "Barbell"
  | "Resistance band"
  | "Bench"
  | "Machine"
  | "Chair / table"
  | "Towel"
  | "Jump rope"
  | "Wall";

export type ExerciseCategory = "push" | "pull" | "legs" | "core" | "skill" | "rest";

export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  primary: MuscleGroup;
  secondary: MuscleGroup[];
  difficulty: Difficulty;
  equipment: Equipment[];
  /** Default prescription */
  sets: number;
  /** Reps string, e.g. "12" or "8 each side" */
  reps?: string;
  /** Seconds, for holds / timed work */
  duration?: number;
  rest: number;
  summary: string;
  /** FORM */
  setup: string;
  steps: string[];
  breathing: string;
  rom: string;
  feel: string;
  mistakes: string[];
  safety: string[];
  beginner: string;
  progressionId?: string;
  regressionId?: string;
  /** Same-muscle swaps when equipment is missing */
  alternativeIds: string[];
}

const E = (e: Exercise) => e;

export const EXERCISES: Exercise[] = [
  /* ---------------------------------- PUSH --------------------------------- */
  E({
    id: "pushup",
    name: "Push-up (Standard)",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Shoulders", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 4,
    reps: "10–15",
    rest: 75,
    summary: "The foundation of all pressing strength. Builds chest, triceps and a braced core.",
    setup:
      "Hands under the shoulders or slightly wider, fingers spread. Legs straight, feet hip-width. Body forms one straight line from head to heels.",
    steps: [
      "Brace your core and squeeze your glutes so your hips do not sag.",
      "Bend the elbows and lower your chest toward the floor, elbows tracking back at roughly 45° from your body.",
      "Stop when your chest is about a fist's height from the ground.",
      "Press the floor away and return to the start without locking out aggressively.",
    ],
    breathing: "Inhale on the way down, exhale as you press up.",
    rom: "Chest to within a few centimetres of the floor, elbows fully but gently extended at the top.",
    feel: "Chest and triceps working; core tight the whole time.",
    mistakes: [
      "Hips sagging or piking up",
      "Elbows flaring straight out to the sides",
      "Head dropping forward instead of a neutral neck",
      "Only doing half the range",
    ],
    safety: ["Stop if you feel sharp shoulder or wrist pain.", "Use fists or push-up handles if wrists are sensitive."],
    beginner: "Do them on an incline (hands on a table or sofa) and lower the surface as you get stronger.",
    progressionId: "pushup-decline",
    regressionId: "pushup-incline",
    alternativeIds: ["pushup-incline", "pushup-knee", "pushup-negative"],
  }),
  E({
    id: "pushup-incline",
    name: "Push-up (Incline)",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Shoulders"],
    difficulty: "Beginner",
    equipment: ["Bodyweight", "Chair / table"],
    sets: 3,
    reps: "12",
    rest: 60,
    summary: "An easier push-up angle — the higher the hands, the lighter the load.",
    setup: "Hands on a stable table, bench or wall, shoulder width. Step your feet back so your body is one straight line.",
    steps: [
      "Brace the core and keep the hips in line with the shoulders.",
      "Lower your chest toward the surface with control.",
      "Touch lightly, then press back up.",
    ],
    breathing: "Inhale down, exhale up.",
    rom: "Chest to the edge of the surface.",
    feel: "Upper chest and triceps.",
    mistakes: ["Using an unstable surface", "Bending at the hips", "Rushing the lowering phase"],
    safety: ["Make sure the surface cannot slide."],
    beginner: "Start at wall height — that is the easiest version and still counts.",
    progressionId: "pushup",
    alternativeIds: ["pushup-knee", "pushup"],
  }),
  E({
    id: "pushup-knee",
    name: "Push-up (Knees)",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10–12",
    rest: 60,
    summary: "Full push-up mechanics with less bodyweight to move.",
    setup: "Knees on a soft surface, ankles crossed, hands under the shoulders. Hips pushed forward so shoulders-hips-knees form a line.",
    steps: ["Brace the core.", "Lower the chest with elbows at ~45°.", "Press back up and keep the line from knees to head."],
    breathing: "Inhale down, exhale up.",
    rom: "Chest close to the floor.",
    feel: "Chest and triceps.",
    mistakes: ["Hips folded back behind the knees", "Head leading the movement"],
    safety: ["Pad your knees."],
    beginner: "This is already the beginner option — focus on slow, clean reps.",
    progressionId: "pushup",
    alternativeIds: ["pushup-incline", "pushup"],
  }),
  E({
    id: "pushup-wide",
    name: "Push-up (Wide)",
    category: "push",
    primary: "Chest",
    secondary: ["Shoulders"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "12",
    rest: 75,
    summary: "Hands wider than the shoulders to bias the outer chest.",
    setup: "Hands roughly 1.5 shoulder widths apart, fingers slightly turned out.",
    steps: ["Brace the core.", "Lower with control — the elbows travel out more than a standard push-up.", "Press up."],
    breathing: "Inhale down, exhale up.",
    rom: "Slightly shorter than a standard push-up; do not force the chest to the floor.",
    feel: "A stretch across the chest.",
    mistakes: ["Going too wide, which stresses the shoulders", "Dropping fast at the bottom"],
    safety: ["If the front of your shoulder pinches, bring the hands narrower."],
    beginner: "Do it on an incline first.",
    alternativeIds: ["pushup", "pushup-incline"],
  }),
  E({
    id: "pushup-diamond",
    name: "Push-up (Diamond)",
    category: "push",
    primary: "Triceps",
    secondary: ["Chest", "Shoulders"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "8–10",
    rest: 75,
    summary: "Narrow hand push-up that hammers the triceps.",
    setup: "Index fingers and thumbs touching to form a diamond under the chest.",
    steps: ["Brace the core.", "Lower until your chest touches your hands, keeping elbows close to the ribs.", "Press back up."],
    breathing: "Inhale down, exhale up.",
    rom: "Chest to hands.",
    feel: "Back of the arms burning.",
    mistakes: ["Elbows flaring wide", "Hips sagging", "Hands too far forward"],
    safety: ["Skip if you have wrist pain; use a fist position or dumbbells instead."],
    beginner: "Do diamonds on an incline or on your knees first.",
    regressionId: "pushup",
    alternativeIds: ["tricep-dip-chair", "pushup"],
  }),
  E({
    id: "pushup-decline",
    name: "Push-up (Decline)",
    category: "push",
    primary: "Chest",
    secondary: ["Shoulders", "Triceps"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight", "Chair / table"],
    sets: 3,
    reps: "10",
    rest: 75,
    summary: "Feet elevated, so more bodyweight lands on the upper chest and shoulders.",
    setup: "Feet on a chair or bed, hands on the floor slightly wider than the shoulders.",
    steps: ["Brace hard — the hips want to sag here.", "Lower the chest to the floor.", "Press back up."],
    breathing: "Inhale down, exhale up.",
    rom: "Full, chest near the floor.",
    feel: "Upper chest and front shoulders.",
    mistakes: ["Elevating the feet too high too soon", "Losing the straight-body line"],
    safety: ["Keep the elevation moderate (knee height) until it feels easy."],
    beginner: "Use a low step instead of a chair.",
    regressionId: "pushup",
    alternativeIds: ["pushup", "pike-pushup"],
  }),
  E({
    id: "pike-pushup",
    name: "Pike Push-up",
    category: "push",
    primary: "Shoulders",
    secondary: ["Triceps", "Core"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "8–10",
    rest: 90,
    summary: "The best bodyweight shoulder press — and the first step toward handstand push-ups.",
    setup: "From a push-up position walk the feet in and lift the hips high so your body makes an upside-down V.",
    steps: [
      "Look between your hands, keep the hips high.",
      "Bend the elbows and lower the crown of your head toward the floor just in front of your hands.",
      "Press back up until the arms are straight.",
    ],
    breathing: "Inhale down, exhale up.",
    rom: "Head lightly toward the floor — no head contact needed.",
    feel: "Front and side shoulders.",
    mistakes: ["Hips dropping so it becomes a normal push-up", "Lowering behind the hands"],
    safety: ["Never let your head take bodyweight on the floor."],
    beginner: "Do it with hands elevated on a chair to lighten the load.",
    progressionId: "handstand-wall",
    regressionId: "pushup",
    alternativeIds: ["pike-pushup", "pushup-decline"],
  }),
  E({
    id: "archer-pushup",
    name: "Archer Push-up",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Core"],
    difficulty: "Advanced",
    equipment: ["Bodyweight"],
    sets: 2,
    reps: "5–6 each side",
    rest: 90,
    summary: "A one-arm push-up stepping stone: one arm presses, the other stays straight.",
    setup: "Wide push-up position, hands turned slightly out.",
    steps: [
      "Shift your weight toward one hand as you bend that elbow.",
      "The other arm stays almost straight, sliding out to the side.",
      "Press back to centre and alternate sides.",
    ],
    breathing: "Inhale as you shift and lower, exhale as you press.",
    rom: "Chest to the working hand.",
    feel: "One-sided chest and triceps load, big core brace.",
    mistakes: ["Twisting the hips", "Letting the straight arm bear no weight at all"],
    safety: ["Build up with standard and wide push-ups first."],
    beginner: "Not a beginner move — use wide push-ups instead.",
    regressionId: "pushup-wide",
    alternativeIds: ["pushup-wide", "pushup"],
  }),
  E({
    id: "pseudo-planche-pushup",
    name: "Pseudo Planche Push-up",
    category: "push",
    primary: "Shoulders",
    secondary: ["Chest", "Core"],
    difficulty: "Advanced",
    equipment: ["Bodyweight"],
    sets: 2,
    reps: "6–8",
    rest: 90,
    summary: "Hands at the waist and shoulders leaning forward — serious straight-arm shoulder strength.",
    setup: "Push-up position with hands near the hips, fingers pointing back or out, shoulders leaning past the hands.",
    steps: ["Lean forward so your shoulders are ahead of your wrists.", "Lower with elbows close to the body.", "Press back up keeping the lean."],
    breathing: "Inhale down, exhale up.",
    rom: "Short but very loaded — do not chase depth.",
    feel: "Front shoulders and upper chest.",
    mistakes: ["Losing the forward lean", "Wrists forced past their comfortable range"],
    safety: ["Warm up the wrists thoroughly.", "Stop at any elbow or wrist pain."],
    beginner: "Do a light lean from your knees.",
    regressionId: "pushup",
    alternativeIds: ["pike-pushup", "pushup"],
  }),
  E({
    id: "tricep-dip-chair",
    name: "Tricep Dip (Chair / Bench)",
    category: "push",
    primary: "Triceps",
    secondary: ["Shoulders", "Chest"],
    difficulty: "Beginner",
    equipment: ["Chair / table"],
    sets: 3,
    reps: "10–12",
    rest: 75,
    summary: "Easy-access triceps builder using a chair or the edge of a bed.",
    setup: "Hands on the edge of a stable chair behind you, fingers forward, legs out in front, heels on the floor.",
    steps: ["Keep your back close to the chair.", "Bend the elbows straight back and lower until they reach about 90°.", "Press back up."],
    breathing: "Inhale down, exhale up.",
    rom: "Elbows to ~90°, no deeper.",
    feel: "Back of the arms.",
    mistakes: ["Dropping too deep and straining the shoulder", "Elbows flaring out", "Hips drifting away from the chair"],
    safety: ["If the front of your shoulder hurts, reduce depth or switch to diamond push-ups."],
    beginner: "Bend the knees and keep your feet closer.",
    progressionId: "dips-bar",
    alternativeIds: ["pushup-diamond", "dips-bar"],
  }),
  E({
    id: "dips-bar",
    name: "Dips (Parallel Bars)",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Shoulders"],
    difficulty: "Advanced",
    equipment: ["Pull-up bar"],
    sets: 3,
    reps: "6–8",
    rest: 90,
    summary: "One of the strongest upper-body pressing movements.",
    setup: "Support yourself on parallel bars, arms straight, shoulders pushed down away from the ears.",
    steps: [
      "Lean the torso slightly forward.",
      "Lower until your upper arms are roughly parallel to the floor.",
      "Press back up without shrugging.",
    ],
    breathing: "Inhale down, exhale up.",
    rom: "Upper arm to parallel — do not sink lower while learning.",
    feel: "Lower chest and triceps.",
    mistakes: ["Shrugging at the bottom", "Bouncing out of the bottom", "Going too deep too early"],
    safety: ["Skip dips entirely if you feel shoulder pinching; use chair dips instead."],
    beginner: "Use chair dips or band-assisted dips.",
    regressionId: "tricep-dip-chair",
    alternativeIds: ["tricep-dip-chair", "pushup-decline"],
  }),
  E({
    id: "plank-shoulder-tap",
    name: "Plank Shoulder Tap",
    category: "push",
    primary: "Core",
    secondary: ["Shoulders"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "20 taps",
    rest: 45,
    summary: "Anti-rotation core work with a shoulder stability bonus.",
    setup: "High plank, feet a little wider than usual for stability.",
    steps: ["Brace hard.", "Lift one hand and tap the opposite shoulder.", "Replace it and alternate — keep the hips completely still."],
    breathing: "Steady, do not hold your breath.",
    rom: "Just a light tap.",
    feel: "Deep core fighting rotation.",
    mistakes: ["Hips rocking side to side", "Going too fast"],
    safety: ["Drop to knees if the lower back arches."],
    beginner: "Do it from the knees.",
    alternativeIds: ["plank", "pushup"],
  }),
  E({
    id: "wall-pushup",
    name: "Wall Push-up",
    category: "push",
    primary: "Chest",
    secondary: ["Shoulders", "Triceps"],
    difficulty: "Beginner",
    equipment: ["Wall"],
    sets: 3,
    reps: "12-15",
    rest: 45,
    summary: "The gentlest entry point to pressing - perfect for a true first week.",
    setup: "Stand an arm's length from a wall, hands at chest height, shoulder width. Feet together, body in one line.",
    steps: [
      "Brace the core so the hips stay in line.",
      "Bend the elbows and bring your chest toward the wall.",
      "Touch lightly, then press the wall away.",
    ],
    breathing: "Inhale in, exhale pressing away.",
    rom: "Chest close to the wall, arms gently straight at the end.",
    feel: "Light chest and triceps effort.",
    mistakes: ["Standing too close so it becomes too easy", "Letting the hips lead", "Rushing the reps"],
    safety: ["Check the wall is dry and your feet will not slip."],
    beginner: "Stand closer to the wall for less load.",
    progressionId: "pushup-incline",
    alternativeIds: ["pushup-incline", "pushup-knee"],
  }),
  E({
    id: "pushup-negative",
    name: "Push-up (Slow Negative)",
    category: "push",
    primary: "Chest",
    secondary: ["Triceps", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "5 slow",
    rest: 75,
    summary: "The fastest honest route to your first full push-ups: control the way down.",
    setup: "Full push-up position, hands under the shoulders, body in one straight line.",
    steps: [
      "Lower yourself for a slow count of four or five.",
      "Touch the chest lightly to the floor.",
      "Drop to the knees, reset to the top, and repeat.",
    ],
    breathing: "Inhale on the long descent, exhale on the reset.",
    rom: "Full descent to the floor - that is the whole point.",
    feel: "Chest and triceps under long tension.",
    mistakes: ["Dropping fast", "Hips sagging near the floor", "Skipping the reset"],
    safety: ["Stop the set once the descent can no longer be controlled."],
    beginner: "Count to three instead of five.",
    progressionId: "pushup",
    regressionId: "pushup-knee",
    alternativeIds: ["pushup-knee", "pushup-incline"],
  }),
  E({
    id: "pike-pushup-elevated",
    name: "Elevated Pike Push-up",
    category: "push",
    primary: "Shoulders",
    secondary: ["Triceps", "Core"],
    difficulty: "Advanced",
    equipment: ["Bodyweight", "Chair / table"],
    sets: 3,
    reps: "6-8",
    rest: 90,
    summary: "Feet raised makes the pike push-up almost vertical - real overhead pressing strength, no weights.",
    setup: "Feet on a stable chair or sofa, hands on the floor, hips stacked high over the shoulders in an inverted V.",
    steps: [
      "Keep the hips high and the back straight.",
      "Bend the elbows and lower the crown of the head toward the floor between your hands.",
      "Press back up until the arms are straight.",
    ],
    breathing: "Inhale down, exhale pressing up.",
    rom: "Head lightly toward the floor, full press at the top.",
    feel: "Shoulders and triceps, core holding the shape.",
    mistakes: ["Hips dropping so it becomes a decline push-up", "Head crashing down", "Elbows flaring wide"],
    safety: ["Use a stable surface only.", "Come down if you feel pressure in the head or neck."],
    beginner: "Do the floor pike push-up first.",
    regressionId: "pike-pushup",
    progressionId: "handstand-wall",
    alternativeIds: ["pike-pushup", "handstand-wall"],
  }),

  /* ---------------------------------- PULL --------------------------------- */
  E({
    id: "table-row",
    name: "Door Frame / Table Row",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Forearms"],
    difficulty: "Beginner",
    equipment: ["Chair / table"],
    sets: 4,
    reps: "12",
    rest: 75,
    summary: "The no-equipment answer to rows — pull your own bodyweight under a sturdy table.",
    setup: "Lie under a sturdy table, grip the edge with both hands, heels on the floor, body straight.",
    steps: [
      "Squeeze your shoulder blades together first.",
      "Pull your chest toward the edge of the table.",
      "Lower slowly until the arms are straight but the shoulders stay set.",
    ],
    breathing: "Exhale as you pull, inhale as you lower.",
    rom: "Chest close to the table, arms fully straight at the bottom.",
    feel: "Mid-back squeezing, biceps helping.",
    mistakes: ["Yanking with the arms before the shoulder blades move", "Hips sagging", "Using an unstable table"],
    safety: ["Test that the table takes your weight before hanging under it."],
    beginner: "Bend your knees and put your feet flat to reduce the load.",
    progressionId: "australian-pullup",
    alternativeIds: ["towel-row", "band-row", "australian-pullup"],
  }),
  E({
    id: "towel-row",
    name: "Towel Row",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps"],
    difficulty: "Beginner",
    equipment: ["Towel", "Chair / table"],
    sets: 3,
    reps: "12",
    rest: 60,
    summary: "A towel looped around a fixed post turns any doorway into a rowing station.",
    setup: "Loop a strong towel around a sturdy post or closed door handle. Hold both ends, lean back with straight arms, feet forward.",
    steps: ["Set the shoulder blades back and down.", "Pull yourself upright toward your hands.", "Lower under control."],
    breathing: "Exhale pulling, inhale lowering.",
    rom: "Arms straight to hands at the ribs.",
    feel: "Mid-back and biceps.",
    mistakes: ["Rounding the back", "Letting the hips lead"],
    safety: ["Check the anchor point and the towel for wear."],
    beginner: "Stand more upright — the more upright you are, the easier it is.",
    alternativeIds: ["table-row", "band-row"],
  }),
  E({
    id: "band-row",
    name: "Resistance Band Row",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Forearms"],
    difficulty: "Beginner",
    equipment: ["Resistance band"],
    sets: 3,
    reps: "15",
    rest: 60,
    summary: "Scalable back work anywhere — a band around your feet or a door anchor.",
    setup: "Sit or stand with the band anchored in front of you at chest height, arms straight.",
    steps: ["Pull the shoulder blades back first.", "Row the handles to the sides of your ribs.", "Return slowly against the band's pull."],
    breathing: "Exhale pulling, inhale returning.",
    rom: "Full arm extension to elbows behind the ribs.",
    feel: "Squeeze between the shoulder blades.",
    mistakes: ["Shrugging the shoulders up", "Letting the band snap you forward"],
    safety: ["Inspect the band for tears before every session."],
    beginner: "Use a lighter band or step closer to the anchor.",
    alternativeIds: ["table-row", "towel-row"],
  }),
  E({
    id: "pullup",
    name: "Pull-up",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Forearms", "Core"],
    difficulty: "Advanced",
    equipment: ["Pull-up bar"],
    sets: 3,
    reps: "4–6",
    rest: 120,
    summary: "The benchmark upper-body pull.",
    setup: "Overhand grip slightly wider than shoulders, hang with straight arms, shoulders pulled down away from the ears.",
    steps: [
      "Start by depressing the shoulder blades (a scapular pull).",
      "Drive the elbows down toward your ribs and pull your chin above the bar.",
      "Lower all the way to a straight-arm hang with control.",
    ],
    breathing: "Exhale on the way up, inhale on the way down.",
    rom: "Dead hang to chin over the bar.",
    feel: "Lats, upper back, biceps.",
    mistakes: ["Kipping/swinging when the goal is strict", "Half reps at the bottom", "Chin craning over the bar"],
    safety: ["Check the bar is secure.", "Build up with scapular pulls and Australian rows first."],
    beginner: "Do negatives: jump to the top and lower for 5 seconds.",
    progressionId: "typewriter-pullup",
    regressionId: "australian-pullup",
    alternativeIds: ["australian-pullup", "table-row", "band-row"],
  }),
  E({
    id: "chinup",
    name: "Chin-up",
    category: "pull",
    primary: "Biceps",
    secondary: ["Back", "Forearms"],
    difficulty: "Intermediate",
    equipment: ["Pull-up bar"],
    sets: 3,
    reps: "5–6",
    rest: 120,
    summary: "Underhand grip pull-up — easier than a pull-up and more biceps.",
    setup: "Underhand grip, hands shoulder-width, straight-arm hang.",
    steps: ["Pull the shoulder blades down.", "Pull the chest toward the bar.", "Lower slowly to a full hang."],
    breathing: "Exhale up, inhale down.",
    rom: "Full hang to chin over bar.",
    feel: "Biceps and lats.",
    mistakes: ["Swinging", "Stopping short at the bottom"],
    safety: ["If your elbows ache, widen the grip slightly."],
    beginner: "Use negatives or a band for assistance.",
    regressionId: "australian-pullup",
    alternativeIds: ["pullup", "table-row"],
  }),
  E({
    id: "australian-pullup",
    name: "Australian Pull-up (Bodyweight Row)",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Core"],
    difficulty: "Beginner",
    equipment: ["Pull-up bar", "Chair / table"],
    sets: 4,
    reps: "10–12",
    rest: 75,
    summary: "A horizontal pull under a low bar — the best pull-up preparation.",
    setup: "Lie under a waist-height bar, grip overhand, body straight, heels on the ground.",
    steps: ["Retract the shoulder blades.", "Pull your chest to the bar.", "Lower fully with control."],
    breathing: "Exhale up, inhale down.",
    rom: "Straight arms to chest touching the bar.",
    feel: "Mid-back.",
    mistakes: ["Hips sagging", "Only pulling with the arms"],
    safety: ["Keep the bar at a height you can control."],
    beginner: "Raise the bar higher or bend the knees.",
    progressionId: "pullup",
    alternativeIds: ["table-row", "band-row"],
  }),
  E({
    id: "scapula-pull",
    name: "Scapular Pull",
    category: "pull",
    primary: "Back",
    secondary: ["Shoulders"],
    difficulty: "Beginner",
    equipment: ["Pull-up bar"],
    sets: 3,
    reps: "10",
    rest: 60,
    summary: "Teaches the shoulder-blade movement that makes pull-ups possible.",
    setup: "Dead hang from the bar with straight arms.",
    steps: ["Without bending the elbows, pull your shoulder blades down and together so your body rises a few centimetres.", "Hold one second.", "Relax back to a full hang."],
    breathing: "Exhale as you pull down, inhale as you release.",
    rom: "Small — only the shoulder blades move.",
    feel: "The muscles under and between your shoulder blades.",
    mistakes: ["Bending the elbows", "Shrugging up instead of pulling down"],
    safety: ["Keep the movement slow; no swinging."],
    beginner: "Do the same motion in a table row position.",
    alternativeIds: ["table-row", "band-row"],
  }),
  E({
    id: "superman-hold",
    name: "Superman Hold",
    category: "pull",
    primary: "Back",
    secondary: ["Glutes", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 20,
    rest: 45,
    summary: "Strengthens the whole back chain with zero equipment.",
    setup: "Lie face down, arms extended in front, legs straight.",
    steps: ["Lift the chest, arms and legs a few centimetres off the floor.", "Keep the neck neutral — look at the floor.", "Hold, then lower with control."],
    breathing: "Breathe normally throughout the hold.",
    rom: "Small lift; height is not the point.",
    feel: "Lower back, glutes and upper back.",
    mistakes: ["Cranking the neck up", "Lifting as high as possible and compressing the lower back"],
    safety: ["Stop if the lower back pinches."],
    beginner: "Lift only the arms, then only the legs.",
    alternativeIds: ["reverse-snow-angel", "glute-bridge"],
  }),
  E({
    id: "reverse-snow-angel",
    name: "Reverse Snow Angel",
    category: "pull",
    primary: "Shoulders",
    secondary: ["Back"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "15",
    rest: 45,
    summary: "Great posture work for the upper back and rear shoulders.",
    setup: "Lie face down, arms by your sides, palms down, chest lightly lifted.",
    steps: ["Sweep the arms out and overhead along the floor without touching it.", "Sweep back to your sides.", "Keep the chest slightly lifted the whole time."],
    breathing: "Slow and steady.",
    rom: "As far overhead as you can go without shrugging.",
    feel: "Rear shoulders and upper back.",
    mistakes: ["Rushing", "Letting the chest drop"],
    safety: ["Keep the neck relaxed."],
    beginner: "Do a smaller arc.",
    alternativeIds: ["superman-hold", "band-row"],
  }),
  E({
    id: "archer-row",
    name: "Archer Row",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Core"],
    difficulty: "Intermediate",
    equipment: ["Pull-up bar", "Chair / table"],
    sets: 3,
    reps: "8 each side",
    rest: 75,
    summary: "One-sided row that builds toward single-arm pulling strength.",
    setup: "Bodyweight row setup with a wide grip.",
    steps: ["Pull your chest toward one hand while the other arm stays straight.", "Lower with control.", "Alternate sides."],
    breathing: "Exhale pulling, inhale lowering.",
    rom: "Chest toward the working hand.",
    feel: "One-sided back and biceps.",
    mistakes: ["Rotating the hips", "Half range"],
    safety: ["Master even bodyweight rows first."],
    beginner: "Do regular Australian pull-ups.",
    regressionId: "australian-pullup",
    alternativeIds: ["australian-pullup", "table-row"],
  }),
  E({
    id: "iso-bicep-hold",
    name: "Isometric Biceps Hold",
    category: "pull",
    primary: "Biceps",
    secondary: ["Forearms"],
    difficulty: "Beginner",
    equipment: ["Towel", "Bodyweight"],
    sets: 3,
    duration: 30,
    rest: 45,
    summary: "Self-resisted biceps tension — no equipment needed.",
    setup: "Loop a towel under one foot (or press hand against hand), elbow bent at 90°.",
    steps: ["Pull up against the resistance without moving.", "Keep the elbow pinned to your side.", "Hold, then switch arms."],
    breathing: "Breathe steadily — do not hold your breath.",
    rom: "None — this is a static hold at 90°.",
    feel: "Constant biceps tension.",
    mistakes: ["Holding the breath", "Letting the elbow drift forward"],
    safety: ["Keep effort at ~70%, not maximal straining."],
    beginner: "Shorten the hold to 15 seconds.",
    alternativeIds: ["band-row", "chinup"],
  }),
  E({
    id: "reverse-fly",
    name: "Reverse Fly",
    category: "pull",
    primary: "Shoulders",
    secondary: ["Back"],
    difficulty: "Beginner",
    equipment: ["Bodyweight", "Resistance band"],
    sets: 3,
    reps: "15",
    rest: 60,
    summary: "Rear-shoulder work that balances all the pushing you do.",
    setup: "Hinge forward at the hips with a flat back, arms hanging, slight elbow bend.",
    steps: ["Lift the arms out to the sides like wings.", "Squeeze the shoulder blades at the top.", "Lower slowly."],
    breathing: "Exhale lifting, inhale lowering.",
    rom: "Up to shoulder height, no higher.",
    feel: "Back of the shoulders.",
    mistakes: ["Using momentum", "Rounding the back", "Going too heavy"],
    safety: ["Keep the load light — this is a small muscle."],
    beginner: "Do it with no weight at all first.",
    alternativeIds: ["reverse-snow-angel", "band-row"],
  }),
  E({
    id: "typewriter-pullup",
    name: "Typewriter Pull-up",
    category: "pull",
    primary: "Back",
    secondary: ["Biceps", "Core"],
    difficulty: "Advanced",
    equipment: ["Pull-up bar"],
    sets: 2,
    reps: "4–6",
    rest: 120,
    summary: "Pull up, then shift side to side at the top. Serious one-arm preparation.",
    setup: "Wide overhand grip, hang with straight arms.",
    steps: ["Pull up to chin height.", "Shift your chest toward one hand while the other arm straightens.", "Shift back across, then lower."],
    breathing: "Exhale pulling, breathe steadily while shifting.",
    rom: "Stay above bar height while shifting.",
    feel: "One-sided lat load.",
    mistakes: ["Dropping below the bar mid-shift", "Swinging"],
    safety: ["Only attempt with 8+ strict pull-ups."],
    beginner: "Not a beginner move — do Australian pull-ups.",
    regressionId: "pullup",
    alternativeIds: ["pullup", "archer-row"],
  }),
  E({
    id: "front-lever-tuck",
    name: "Tuck Front Lever",
    category: "skill",
    primary: "Core",
    secondary: ["Back", "Shoulders"],
    difficulty: "Advanced",
    equipment: ["Pull-up bar"],
    sets: 3,
    duration: 10,
    rest: 90,
    summary: "A straight-arm hanging hold with the knees tucked — the first front lever step.",
    setup: "Hang from the bar with straight arms, overhand grip.",
    steps: ["Pull the shoulder blades down and push the bar slightly forward.", "Tuck the knees to the chest and lift the hips until the back is parallel to the ground.", "Hold, then lower under control."],
    breathing: "Short, steady breaths — never hold your breath.",
    rom: "Back parallel to the floor.",
    feel: "Lats and deep core working hard together.",
    mistakes: ["Bending the elbows", "Hips too low", "Holding the breath"],
    safety: ["Build up with scapular pulls and hollow holds first."],
    beginner: "Practise hollow body holds on the floor instead.",
    regressionId: "hollow-hold",
    alternativeIds: ["hollow-hold", "scapula-pull"],
  }),

  /* ---------------------------------- LEGS --------------------------------- */
  E({
    id: "squat",
    name: "Bodyweight Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 4,
    reps: "15–20",
    rest: 75,
    summary: "The base pattern for every lower-body exercise.",
    setup: "Feet shoulder-width, toes slightly out, chest tall, arms forward for balance.",
    steps: [
      "Push the hips back and bend the knees together.",
      "Descend until the thighs are about parallel to the floor (or as low as you can with a flat back).",
      "Drive through the whole foot and stand tall, squeezing the glutes at the top.",
    ],
    breathing: "Inhale down, exhale up.",
    rom: "Thighs to parallel or below, heels flat.",
    feel: "Thighs and glutes.",
    mistakes: ["Heels lifting", "Knees collapsing inward", "Rounding the lower back at the bottom"],
    safety: ["Never force depth — go as low as you can control."],
    beginner: "Squat to a chair and stand back up.",
    progressionId: "bulgarian-split-squat",
    alternativeIds: ["wall-sit", "lunge", "squat-tempo"],
  }),
  E({
    id: "squat-tempo",
    name: "Tempo Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10 slow",
    rest: 75,
    summary: "Slowing the squat down builds strength and control without any load.",
    setup: "Feet shoulder-width, toes slightly out, chest tall, arms forward for balance.",
    steps: [
      "Lower for a slow count of three.",
      "Pause for one count at the bottom, thighs at least parallel if your hips allow.",
      "Stand up smoothly without locking the knees hard.",
    ],
    breathing: "Inhale down, exhale standing up.",
    rom: "As deep as you can keep the heels down and the back neutral.",
    feel: "Quads and glutes working through the whole range.",
    mistakes: ["Heels lifting", "Knees caving inward", "Bouncing out of the bottom"],
    safety: ["Squat to a chair if balance is shaky."],
    beginner: "Hold a door frame lightly for balance.",
    regressionId: "squat",
    progressionId: "bulgarian-split-squat",
    alternativeIds: ["squat", "wall-sit"],
  }),
  E({
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    category: "legs",
    primary: "Glutes",
    secondary: ["Legs", "Core"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10 each side",
    rest: 60,
    summary: "One leg at a time exposes and fixes side-to-side differences in the hips.",
    setup: "Lie on your back, one foot planted close to the hips, the other leg extended or knee hugged in.",
    steps: [
      "Press through the planted heel and lift the hips until the body is in one line.",
      "Squeeze the glute hard at the top for a full second.",
      "Lower with control and repeat, then swap sides.",
    ],
    breathing: "Exhale lifting, inhale lowering.",
    rom: "Hips level with the shoulders and knee at the top - no over-arching.",
    feel: "The glute on the working side, not the lower back.",
    mistakes: ["Arching the lower back instead of extending the hips", "Hips tilting to one side", "Pushing through the toes"],
    safety: ["Reduce range if you feel it in the lower back."],
    beginner: "Do the two-leg glute bridge until 15 clean reps feel easy.",
    regressionId: "glute-bridge",
    alternativeIds: ["glute-bridge", "lunge"],
  }),
  E({
    id: "pistol-squat-assisted",
    name: "Assisted Pistol Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight", "Chair / table"],
    sets: 3,
    reps: "5 each side",
    rest: 90,
    summary: "The bridge to a full one-leg squat - hold on for just as much help as you need.",
    setup: "Stand on one leg beside a door frame or sturdy chair, other leg straight out in front, one hand lightly on the support.",
    steps: [
      "Sit back and down on the standing leg, keeping the heel planted.",
      "Descend as low as you can control, using the support minimally.",
      "Drive up through the whole foot and stand tall.",
    ],
    breathing: "Inhale down, exhale up.",
    rom: "As deep as your control and ankle mobility allow - depth comes with time.",
    feel: "Standing-leg quad and glute, plus a lot of balance work.",
    mistakes: ["Pulling hard on the support", "Heel lifting", "Knee collapsing inward"],
    safety: ["Do not force depth; the knee should never feel pinched."],
    beginner: "Squat down to a chair on one leg first.",
    regressionId: "bulgarian-split-squat",
    progressionId: "pistol-squat",
    alternativeIds: ["bulgarian-split-squat", "lunge"],
  }),
  E({
    id: "pistol-squat",
    name: "Pistol Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Advanced",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "3-5 each side",
    rest: 120,
    summary: "A full unassisted one-leg squat: leg strength, balance and mobility in one movement.",
    setup: "Stand on one leg, other leg extended forward, arms out in front as a counterweight.",
    steps: [
      "Sit back and lower slowly all the way down, keeping the free leg off the floor.",
      "Pause briefly at the bottom without collapsing.",
      "Stand back up through the whole foot.",
    ],
    breathing: "Inhale on the descent, exhale standing up.",
    rom: "Full depth with the heel down.",
    feel: "Everything in the standing leg, plus deep core and balance work.",
    mistakes: ["Falling backward at the bottom", "Heel rising", "Rounding the back to reach depth"],
    safety: ["Only progress here once assisted pistols are clean and pain-free."],
    beginner: "Go back to the assisted version and reduce the help gradually.",
    regressionId: "pistol-squat-assisted",
    alternativeIds: ["pistol-squat-assisted", "bulgarian-split-squat"],
  }),
  E({
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Intermediate",
    equipment: ["Chair / table", "Bodyweight"],
    sets: 3,
    reps: "10 each leg",
    rest: 90,
    summary: "Brutally effective single-leg strength and balance.",
    setup: "Stand about a stride ahead of a chair, place the top of one foot on it.",
    steps: ["Keep the torso mostly upright.", "Lower the back knee toward the floor.", "Drive up through the front heel."],
    breathing: "Inhale down, exhale up.",
    rom: "Back knee close to the floor, front thigh near parallel.",
    feel: "Front-leg quad and glute.",
    mistakes: ["Front foot too close to the chair", "Knee caving inward", "Losing balance and rushing"],
    safety: ["Hold a wall for balance if needed."],
    beginner: "Do split squats with the back foot on the floor.",
    regressionId: "lunge",
    alternativeIds: ["lunge", "squat"],
  }),
  E({
    id: "lunge",
    name: "Lunge",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "12 each leg",
    rest: 75,
    summary: "Single-leg strength, balance and hip mobility in one move.",
    setup: "Stand tall, feet hip-width, hands on hips.",
    steps: ["Step forward into a long stride.", "Lower until both knees are around 90°.", "Push off the front foot to return to standing."],
    breathing: "Inhale down, exhale up.",
    rom: "Back knee to just above the floor.",
    feel: "Front-leg quad and glute.",
    mistakes: ["Short steps that put all load on the knee", "Leaning too far forward", "Front knee collapsing in"],
    safety: ["Use a wall for balance if unsteady."],
    beginner: "Do static split squats without stepping.",
    progressionId: "bulgarian-split-squat",
    alternativeIds: ["squat", "bulgarian-split-squat"],
  }),
  E({
    id: "wall-sit",
    name: "Wall Sit",
    category: "legs",
    primary: "Legs",
    secondary: ["Core"],
    difficulty: "Beginner",
    equipment: ["Wall"],
    sets: 3,
    duration: 40,
    rest: 60,
    summary: "A simple isometric that builds quad endurance and mental toughness.",
    setup: "Back flat against a wall, slide down until the thighs are parallel to the floor, knees over the ankles.",
    steps: ["Press the whole back into the wall.", "Keep the weight in the heels.", "Hold for time, breathing steadily."],
    breathing: "Steady breathing — do not brace and hold your breath.",
    rom: "Static.",
    feel: "Burning quads.",
    mistakes: ["Knees past the toes", "Hands resting on the thighs", "Sliding up as it gets hard"],
    safety: ["Stop if the knees hurt rather than burn."],
    beginner: "Sit higher (a shallower knee bend) and hold 20 seconds.",
    alternativeIds: ["squat", "lunge"],
  }),
  E({
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "legs",
    primary: "Glutes",
    secondary: ["Legs", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "15",
    rest: 45,
    summary: "Direct glute work that also helps lower-back comfort.",
    setup: "Lie on your back, knees bent, feet flat and hip-width, arms by your sides.",
    steps: ["Press through the heels and lift the hips until your body forms a straight line from knees to shoulders.", "Squeeze the glutes at the top for a second.", "Lower with control."],
    breathing: "Exhale lifting, inhale lowering.",
    rom: "Hips to a straight line — do not over-arch.",
    feel: "Glutes, not lower back.",
    mistakes: ["Pushing through the toes", "Arching the lower back at the top"],
    safety: ["If you feel it in your lower back, tuck the pelvis slightly and lift less high."],
    beginner: "Hold the top position for 5 seconds per rep.",
    alternativeIds: ["squat", "sumo-walk"],
  }),
  E({
    id: "calf-raise",
    name: "Calf Raise",
    category: "legs",
    primary: "Calves",
    secondary: [],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "20",
    rest: 45,
    summary: "Builds ankle strength and calf size.",
    setup: "Stand tall, feet hip-width, fingertips on a wall for balance.",
    steps: ["Rise onto the balls of your feet as high as possible.", "Pause one second at the top.", "Lower slowly until the heels touch."],
    breathing: "Exhale up, inhale down.",
    rom: "Full stretch at the bottom, full squeeze at the top.",
    feel: "Calves.",
    mistakes: ["Bouncing", "Tiny range of motion"],
    safety: ["Hold a wall to avoid rolling an ankle."],
    beginner: "Both legs, on flat ground.",
    alternativeIds: ["squat", "jump-rope"],
  }),
  E({
    id: "lateral-squat",
    name: "Lateral Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Mobility"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10 each side",
    rest: 60,
    summary: "Side-to-side squatting for inner thighs and hip mobility.",
    setup: "Stand with feet very wide, toes forward.",
    steps: ["Shift your weight to one side, bending that knee while the other leg stays straight.", "Keep the chest up and the foot flat.", "Push back to centre and swap sides."],
    breathing: "Inhale shifting, exhale returning.",
    rom: "As deep as you can with a flat foot and neutral back.",
    feel: "Bent-leg quad and glute, straight-leg inner thigh stretch.",
    mistakes: ["Heel lifting", "Rounding the back"],
    safety: ["Ease into depth — the inner thigh stretches here."],
    beginner: "Take a narrower stance and go shallow.",
    alternativeIds: ["squat", "lunge"],
  }),
  E({
    id: "jump-squat",
    name: "Jump Squat",
    category: "legs",
    primary: "Legs",
    secondary: ["Glutes", "Calves"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10",
    rest: 90,
    summary: "Explosive power and a strong conditioning hit.",
    setup: "Feet shoulder-width, arms ready to swing.",
    steps: ["Squat to about half depth.", "Jump up explosively, extending the hips fully.", "Land softly on the mid-foot and absorb into the next squat."],
    breathing: "Exhale on the jump.",
    rom: "Half squat, full extension in the air.",
    feel: "Powerful legs and glutes; elevated heart rate.",
    mistakes: ["Landing with stiff, locked legs", "Loud, heavy landings", "Doing them fatigued with sloppy form"],
    safety: ["Skip jumps if you have knee pain or are on a hard floor without shoes."],
    beginner: "Do fast bodyweight squats without leaving the ground.",
    regressionId: "squat",
    alternativeIds: ["squat", "burpee"],
  }),
  E({
    id: "sumo-walk",
    name: "Sumo Walk",
    category: "legs",
    primary: "Glutes",
    secondary: ["Legs"],
    difficulty: "Beginner",
    equipment: ["Bodyweight", "Resistance band"],
    sets: 3,
    reps: "20 steps",
    rest: 45,
    summary: "Low, wide walking that lights up the glutes and hips.",
    setup: "Half squat position, feet wide, chest up.",
    steps: ["Stay low the whole time.", "Step sideways, keeping tension in the hips.", "Do not stand up between steps."],
    breathing: "Steady.",
    rom: "Stay in the half squat.",
    feel: "Side glutes.",
    mistakes: ["Standing up between steps", "Knees caving in"],
    safety: ["Keep the steps short and controlled."],
    beginner: "Stay a little higher and do fewer steps.",
    alternativeIds: ["glute-bridge", "lateral-squat"],
  }),

  /* ---------------------------------- CORE --------------------------------- */
  E({
    id: "plank",
    name: "Plank",
    category: "core",
    primary: "Core",
    secondary: ["Shoulders", "Glutes"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 40,
    rest: 45,
    summary: "The core's most useful skill: staying rigid under load.",
    setup: "Forearms on the floor under the shoulders, legs straight, feet hip-width.",
    steps: ["Squeeze the glutes and tuck the pelvis slightly.", "Push the forearms into the floor and keep a straight line from head to heels.", "Hold for time with steady breathing."],
    breathing: "Normal breathing throughout — never hold your breath.",
    rom: "Static.",
    feel: "Deep abdominal tension, glutes engaged.",
    mistakes: ["Hips sagging", "Hips too high", "Holding your breath", "Holding on far past good form"],
    safety: ["End the set when the hips start to drop — quality over time."],
    beginner: "Plank from the knees, or hands on a chair.",
    progressionId: "hollow-hold",
    alternativeIds: ["hollow-hold", "plank-shoulder-tap"],
  }),
  E({
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    primary: "Core",
    secondary: ["Legs"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "8 each side",
    rest: 45,
    summary: "Teaches your core to stay braced while the arms and legs move - the base of every other core skill.",
    setup: "Lie on your back, knees bent over the hips, arms straight up toward the ceiling, lower back flat.",
    steps: [
      "Press the lower back gently into the floor.",
      "Lower the opposite arm and leg toward the floor slowly.",
      "Return to the start and switch sides without letting the back arch.",
    ],
    breathing: "Exhale as you extend, inhale as you return.",
    rom: "Extend only as far as the lower back can stay flat.",
    feel: "Deep front-core tension, no lower-back strain.",
    mistakes: ["Lower back arching off the floor", "Moving too fast", "Holding the breath"],
    safety: ["Shorten the range instead of pushing through back discomfort."],
    beginner: "Move only the legs, keeping the arms by your sides.",
    progressionId: "hollow-hold",
    alternativeIds: ["hollow-hold", "plank"],
  }),
  E({
    id: "side-plank",
    name: "Side Plank",
    category: "core",
    primary: "Core",
    secondary: ["Shoulders", "Glutes"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 30,
    rest: 45,
    summary: "Builds the side core and hips that keep your spine stable in everything else.",
    setup: "Lie on your side, forearm on the floor under the shoulder, legs stacked or staggered.",
    steps: [
      "Lift the hips so the body forms one straight line.",
      "Push the bottom shoulder away from the ear and hold.",
      "Lower with control and repeat on the other side.",
    ],
    breathing: "Steady, normal breathing.",
    rom: "Static hold.",
    feel: "The side of your torso and the bottom hip.",
    mistakes: ["Hips sagging toward the floor", "Rolling forward or back", "Sinking into the shoulder"],
    safety: ["Stop the set when the hips start to drop."],
    beginner: "Bend the knees and hold from them instead of the feet.",
    progressionId: "plank-shoulder-tap",
    alternativeIds: ["plank", "hollow-hold"],
  }),
  E({
    id: "hollow-hold",
    name: "Hollow Body Hold",
    category: "core",
    primary: "Core",
    secondary: [],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 20,
    rest: 60,
    summary: "The gymnastics core position underpinning most skill work.",
    setup: "Lie on your back, arms overhead, legs straight.",
    steps: ["Press the lower back flat into the floor.", "Lift the shoulders and legs a few centimetres, keeping the back flat.", "Hold, keeping the ribs down."],
    breathing: "Short, steady breaths.",
    rom: "Static.",
    feel: "Whole front of the torso.",
    mistakes: ["Lower back arching off the floor", "Legs too low for your current strength"],
    safety: ["If the lower back lifts, raise the legs higher or tuck the knees."],
    beginner: "Tuck the knees and keep the arms by your sides.",
    regressionId: "plank",
    alternativeIds: ["plank", "v-up"],
  }),
  E({
    id: "v-up",
    name: "V-Up",
    category: "core",
    primary: "Core",
    secondary: ["Legs"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "12–15",
    rest: 60,
    summary: "A dynamic full-abdominal crunch.",
    setup: "Lie flat, arms overhead, legs straight.",
    steps: ["Lift the arms and legs at the same time to meet over the hips.", "Reach toward your toes.", "Lower with control without slamming down."],
    breathing: "Exhale as you fold up, inhale as you lower.",
    rom: "Full fold to nearly flat.",
    feel: "Whole abdominal wall.",
    mistakes: ["Using momentum", "Yanking the neck", "Slamming the legs down"],
    safety: ["Bend the knees if the lower back complains."],
    beginner: "Do tuck-ups with bent knees.",
    regressionId: "hollow-hold",
    alternativeIds: ["bicycle-crunch", "hollow-hold"],
  }),
  E({
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    primary: "Core",
    secondary: [],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "20 total",
    rest: 45,
    summary: "Hits the obliques through rotation.",
    setup: "Lie on your back, hands lightly behind the head, knees at 90°.",
    steps: ["Lift the shoulders off the floor.", "Bring one elbow toward the opposite knee while extending the other leg.", "Alternate slowly and deliberately."],
    breathing: "Exhale on each rotation.",
    rom: "Rotate from the ribs, not the elbows.",
    feel: "Sides of the abdomen.",
    mistakes: ["Pulling on the neck", "Going fast with tiny rotations"],
    safety: ["Keep the hands light behind the head — never pull."],
    beginner: "Keep both feet closer to the floor and move slowly.",
    alternativeIds: ["v-up", "mountain-climber"],
  }),
  E({
    id: "seated-in-out",
    name: "Seated In-and-Out",
    category: "core",
    primary: "Core",
    secondary: ["Legs"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "15",
    rest: 45,
    summary: "Lower-ab focused, done sitting on the floor.",
    setup: "Sit with hands behind you for support, lean back slightly, feet off the floor.",
    steps: ["Extend the legs out straight while leaning back.", "Pull the knees back toward the chest.", "Keep the feet off the floor the whole set."],
    breathing: "Exhale pulling in, inhale extending.",
    rom: "Legs nearly straight to knees at the chest.",
    feel: "Lower abs.",
    mistakes: ["Feet touching down", "Rounding the back heavily"],
    safety: ["Keep the chest lifted to protect the lower back."],
    beginner: "Extend only halfway.",
    alternativeIds: ["v-up", "hollow-hold"],
  }),
  E({
    id: "mountain-climber",
    name: "Mountain Climber",
    category: "core",
    primary: "Core",
    secondary: ["Full body", "Shoulders"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 30,
    rest: 45,
    summary: "Core plus cardio in a plank position.",
    setup: "High plank, hands under shoulders, body straight.",
    steps: ["Drive one knee toward the chest.", "Switch legs quickly while keeping the hips level.", "Keep a steady rhythm for the full time."],
    breathing: "Quick, rhythmic breathing.",
    rom: "Knee toward the chest without the hips bouncing.",
    feel: "Core, shoulders, elevated heart rate.",
    mistakes: ["Hips bouncing up and down", "Hands drifting forward"],
    safety: ["Slow down before form breaks."],
    beginner: "Do them slowly, one leg at a time.",
    alternativeIds: ["plank", "burpee"],
  }),
  E({
    id: "l-sit",
    name: "L-Sit",
    category: "core",
    primary: "Core",
    secondary: ["Triceps", "Legs"],
    difficulty: "Advanced",
    equipment: ["Bodyweight", "Chair / table"],
    sets: 3,
    duration: 12,
    rest: 90,
    summary: "Supporting your whole body on straight arms with the legs held out front.",
    setup: "Sit on the floor (or two low blocks), hands flat beside the hips, legs straight in front.",
    steps: ["Press the floor down and lock the elbows.", "Lift the hips and then the legs off the floor.", "Hold with the toes pointed."],
    breathing: "Short, steady breaths — no breath holding.",
    rom: "Legs parallel to the floor.",
    feel: "Deep core, hip flexors and triceps.",
    mistakes: ["Shrugging the shoulders", "Bent elbows", "Holding the breath"],
    safety: ["Use blocks or parallettes to save the wrists."],
    beginner: "Do a tuck L-sit with the knees bent.",
    regressionId: "hollow-hold",
    alternativeIds: ["hollow-hold", "plank"],
  }),
  E({
    id: "burpee",
    name: "Burpee",
    category: "core",
    primary: "Full body",
    secondary: ["Legs", "Chest", "Core"],
    difficulty: "Intermediate",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10",
    rest: 75,
    summary: "The classic full-body conditioning move.",
    setup: "Stand tall with space around you.",
    steps: [
      "Squat down and place your hands on the floor.",
      "Jump or step the feet back into a plank, optionally with a push-up.",
      "Jump or step the feet back in and stand or jump up.",
    ],
    breathing: "Find a rhythm; do not hold your breath.",
    rom: "Full plank and full stand each rep.",
    feel: "Everything — legs, chest, lungs.",
    mistakes: ["Sagging hips in the plank", "Landing hard", "Going too fast to keep form"],
    safety: ["Step instead of jumping if your knees or wrists are irritated."],
    beginner: "Step back and step in, no jump, no push-up.",
    alternativeIds: ["mountain-climber", "jump-rope"],
  }),
  E({
    id: "jump-rope",
    name: "Jump Rope / Skipping",
    category: "core",
    primary: "Full body",
    secondary: ["Calves", "Core"],
    difficulty: "Beginner",
    equipment: ["Jump rope", "Bodyweight"],
    sets: 1,
    duration: 480,
    rest: 60,
    summary: "Efficient, joint-friendly-ish cardio you can do in one square metre.",
    setup: "Rope handles at hip height, elbows close to the body, eyes forward.",
    steps: ["Turn the rope with the wrists, not the arms.", "Take small, low bounces on the balls of your feet.", "Break into intervals (e.g. 45s on, 30s off) if you are new."],
    breathing: "Steady rhythm; slow down if you cannot breathe through your nose.",
    rom: "Small hops, only a couple of centimetres off the floor.",
    feel: "Calves and lungs.",
    mistakes: ["Jumping far too high", "Swinging the whole arm", "Landing on the heels"],
    safety: ["Wear shoes on hard floors.", "Do imaginary skipping if you have no rope."],
    beginner: "Start with 30-second rounds and plenty of rest.",
    alternativeIds: ["burpee", "mountain-climber"],
  }),

  /* --------------------------------- SKILL --------------------------------- */
  E({
    id: "handstand-wall",
    name: "Wall Handstand Hold",
    category: "skill",
    primary: "Shoulders",
    secondary: ["Core", "Forearms"],
    difficulty: "Intermediate",
    equipment: ["Wall"],
    sets: 3,
    duration: 20,
    rest: 90,
    summary: "Builds the shoulder strength and body line for a free handstand.",
    setup: "Hands about 20cm from a wall, shoulder-width, fingers spread.",
    steps: [
      "Walk your feet up the wall (or kick up carefully) until your body is stacked.",
      "Push the floor away, squeeze the glutes and keep the ribs down.",
      "Hold, then come down with control one leg at a time.",
    ],
    breathing: "Small, steady breaths.",
    rom: "Static hold.",
    feel: "Shoulders and core; hands gripping the floor.",
    mistakes: ["Banana back with flared ribs", "Shrugged, collapsed shoulders", "Holding until you fall"],
    safety: ["Clear the space around you.", "Practise coming down safely before going up."],
    beginner: "Start with a wall plank (feet on the wall, hands far away) or a pike hold.",
    regressionId: "pike-pushup",
    alternativeIds: ["pike-pushup", "headstand"],
  }),
  E({
    id: "headstand",
    name: "Headstand (Supported)",
    category: "skill",
    primary: "Core",
    secondary: ["Shoulders", "Mobility"],
    difficulty: "Intermediate",
    equipment: ["Wall", "Bodyweight"],
    sets: 3,
    duration: 20,
    rest: 90,
    summary: "A stable inversion that builds balance and body awareness.",
    setup: "Kneel with forearms down, hands clasped, crown of the head lightly on the floor forming a tripod with the elbows.",
    steps: ["Take most of the weight in the forearms, not the head.", "Walk the feet in and lift the hips over the shoulders.", "Raise the legs slowly, keeping the core tight."],
    breathing: "Slow and calm.",
    rom: "Static.",
    feel: "Shoulders and core; only light pressure on the head.",
    mistakes: ["Loading the neck with bodyweight", "Kicking up hard", "No wall on the first attempts"],
    safety: ["Use a mat and a wall.", "Skip inversions if you have neck problems or high blood pressure."],
    beginner: "Practise the tripod with the knees resting on the elbows.",
    alternativeIds: ["handstand-wall", "plank"],
  }),
  E({
    id: "planche-tuck",
    name: "Tuck Planche",
    category: "skill",
    primary: "Shoulders",
    secondary: ["Core", "Forearms"],
    difficulty: "Advanced",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 8,
    rest: 90,
    summary: "Straight-arm balance with the knees tucked and feet off the floor.",
    setup: "Crouch with hands flat on the floor beside the hips, fingers forward or slightly out, arms locked.",
    steps: ["Lean the shoulders well forward past the hands.", "Push the floor away hard and lift the feet with the knees tucked.", "Hold, then place the feet down under control."],
    breathing: "Steady breathing.",
    rom: "Static.",
    feel: "Front shoulders, biceps and locked elbows.",
    mistakes: ["Bending the elbows", "Not leaning far enough forward", "Cold wrists"],
    safety: ["Warm the wrists and elbows thoroughly.", "Build up with pseudo planche push-ups first."],
    beginner: "Do frog stands (knees resting on the elbows).",
    regressionId: "pseudo-planche-pushup",
    alternativeIds: ["pseudo-planche-pushup", "handstand-wall"],
  }),

  /* ------------------------------ REST / MOBILITY --------------------------- */
  E({
    id: "childs-pose",
    name: "Child's Pose",
    category: "rest",
    primary: "Mobility",
    secondary: ["Back"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 30,
    rest: 15,
    summary: "A restful stretch for the back, hips and shoulders.",
    setup: "Kneel, big toes together, knees wide, sit back onto the heels.",
    steps: ["Walk the hands forward and lower the chest between the thighs.", "Rest the forehead on the floor.", "Breathe into the back of the ribs."],
    breathing: "Slow, deep breaths — 4 seconds in, 6 out.",
    rom: "Comfortable stretch, never painful.",
    feel: "Lower back and hips releasing.",
    mistakes: ["Forcing the hips down", "Holding tension in the shoulders"],
    safety: ["Put a cushion under the hips or knees if needed."],
    beginner: "Keep the knees closer together and use a pillow.",
    alternativeIds: ["cat-cow", "forward-fold"],
  }),
  E({
    id: "bridge-pose",
    name: "Bridge Pose",
    category: "rest",
    primary: "Mobility",
    secondary: ["Glutes", "Back"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 20,
    rest: 20,
    summary: "Opens the hips and chest after a day of sitting.",
    setup: "Lie on your back, knees bent, feet flat and hip-width, arms alongside the body.",
    steps: ["Press the feet down and lift the hips.", "Roll the shoulders under and open the chest.", "Hold, then lower one vertebra at a time."],
    breathing: "Slow and even.",
    rom: "Comfortable lift — this is a stretch, not a max lift.",
    feel: "Hip flexors and chest opening, glutes working lightly.",
    mistakes: ["Cranking the lower back", "Knees splaying out"],
    safety: ["Lower immediately if the lower back pinches."],
    beginner: "Lift halfway and hold briefly.",
    alternativeIds: ["glute-bridge", "cat-cow"],
  }),
  E({
    id: "forward-fold",
    name: "Standing Forward Fold",
    category: "rest",
    primary: "Mobility",
    secondary: ["Legs", "Back"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    duration: 25,
    rest: 15,
    summary: "Hamstring and lower-back decompression.",
    setup: "Stand with feet hip-width, a soft bend in the knees.",
    steps: ["Hinge at the hips and fold forward, letting the head and arms hang.", "Let gravity do the work.", "Roll up slowly to stand."],
    breathing: "Deep breaths; exhale to soften further.",
    rom: "Only as far as a comfortable stretch.",
    feel: "Back of the legs and the spine lengthening.",
    mistakes: ["Locking the knees hard", "Bouncing", "Coming up fast"],
    safety: ["Bend the knees generously if the hamstrings are tight."],
    beginner: "Rest the hands on a chair instead of reaching the floor.",
    alternativeIds: ["childs-pose", "cat-cow"],
  }),
  E({
    id: "cat-cow",
    name: "Cat-Cow",
    category: "rest",
    primary: "Mobility",
    secondary: ["Back", "Core"],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 3,
    reps: "10 rounds",
    rest: 15,
    summary: "Gentle spinal mobility — a perfect warm-up or cool-down.",
    setup: "On hands and knees, hands under shoulders, knees under hips.",
    steps: ["Inhale: drop the belly, lift the chest and tailbone (cow).", "Exhale: round the spine and tuck the chin (cat).", "Move slowly with the breath."],
    breathing: "One full breath per round.",
    rom: "Comfortable, pain-free spinal movement.",
    feel: "The whole spine moving segment by segment.",
    mistakes: ["Moving faster than the breath", "Forcing the range"],
    safety: ["Pad the knees."],
    beginner: "Do smaller movements.",
    alternativeIds: ["childs-pose", "forward-fold"],
  }),
  E({
    id: "savasana",
    name: "Savasana (Rest)",
    category: "rest",
    primary: "Mobility",
    secondary: [],
    difficulty: "Beginner",
    equipment: ["Bodyweight"],
    sets: 1,
    duration: 300,
    rest: 0,
    summary: "Deliberate rest. Recovery is when your training actually pays off.",
    setup: "Lie flat on your back, legs relaxed, arms by your sides, palms up.",
    steps: ["Close the eyes.", "Relax the jaw, shoulders and hands.", "Breathe slowly and let the body be heavy."],
    breathing: "Slow nasal breathing, longer exhale than inhale.",
    rom: "None.",
    feel: "Heart rate falling, muscles softening.",
    mistakes: ["Skipping it because it feels unproductive", "Checking your phone"],
    safety: ["None — this is rest."],
    beginner: "Two minutes is plenty to start.",
    alternativeIds: ["childs-pose"],
  }),
];

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Forearms",
  "Legs",
  "Glutes",
  "Calves",
  "Core",
  "Full body",
  "Mobility",
];

/**
 * Zorvia V2 is home / bodyweight first. Only equipment a person can realistically
 * have at home is offered - no barbells, machines or benches. Legacy values stay in
 * the `Equipment` union so older saved profiles still load without data loss.
 */
export const EQUIPMENT_LIST: Equipment[] = [
  "Bodyweight",
  "Pull-up bar",
  "Chair / table",
  "Wall",
  "Towel",
  "Resistance band",
  "Jump rope",
];

/** Equipment beyond plain bodyweight that is treated as fully optional. */
export const OPTIONAL_EQUIPMENT: Equipment[] = ["Pull-up bar", "Resistance band", "Jump rope", "Towel"];

/** Broad training areas used to browse the library by body region. */
export type MuscleArea =
  | "Chest"
  | "Back"
  | "Shoulders"
  | "Arms"
  | "Legs"
  | "Core"
  | "Full body"
  | "Mobility & skills";

export const MUSCLE_AREAS: MuscleArea[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Legs",
  "Core",
  "Full body",
  "Mobility & skills",
];

const AREA_BY_MUSCLE: Record<MuscleGroup, MuscleArea> = {
  Chest: "Chest",
  Back: "Back",
  Shoulders: "Shoulders",
  Biceps: "Arms",
  Triceps: "Arms",
  Forearms: "Arms",
  Legs: "Legs",
  Glutes: "Legs",
  Calves: "Legs",
  Core: "Core",
  "Full body": "Full body",
  Mobility: "Mobility & skills",
};

export function areaFor(exercise: Exercise): MuscleArea {
  if (exercise.category === "skill") return "Mobility & skills";
  return AREA_BY_MUSCLE[exercise.primary];
}

export function inArea(exercise: Exercise, area: MuscleArea): boolean {
  if (areaFor(exercise) === area) return true;
  return exercise.secondary.some((m) => AREA_BY_MUSCLE[m] === area);
}

export const DIFFICULTIES: Difficulty[] = ["Beginner", "Intermediate", "Advanced"];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}
