/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as FormCheckRouteImport } from './routes/form-check'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const FormCheckRoute = FormCheckRouteImport.update({
  id: '/form-check',
  path: '/form-check',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/form-check': typeof FormCheckRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/form-check': typeof FormCheckRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises': typeof ExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/form-check': typeof FormCheckRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/form-check'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/routines'
    | '/session'
    | '/settings'
    | '/workout'
    | '/exercises/$exerciseId'
    | '/exercises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/form-check'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/routines'
    | '/session'
    | '/settings'
    | '/workout'
    | '/exercises/$exerciseId'
    | '/exercises'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coach'
    | '/form-check'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/routines'
    | '/session'
    | '/settings'
    | '/workout'
    | '/exercises/$exerciseId'
    | '/exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  FormCheckRoute: typeof FormCheckRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoutinesRoute: typeof RoutinesRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  WorkoutRoute: typeof WorkoutRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-check': {
      id: '/form-check'
      path: '/form-check'
      fullPath: '/form-check'
      preLoaderRoute: typeof FormCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  FormCheckRoute: FormCheckRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoutinesRoute: RoutinesRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  WorkoutRoute: WorkoutRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
